
sudo: required
services:
 - docker

script:
- echo "Done"

after_success:
 - docker build -t alphata/web -f MyTestApp.Web/Dockerfile MyTestApp.Web/.
 - docker build -t alphata/api -f MyTestApp.Api/Dockerfile MyTestApp.Api/.
 - docker build -t alphata/worker -f MyTestApp.Worker/Dockerfile MyTestApp.Worker/.
 - docker build -t alphata/nginx -f nginx/Dockerfile .

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push alphata/web
 - docker push alphata/api
 - docker push alphata/worker
 - docker push alphata/nginx