
sudo: required
services:
 - docker

before_install:
 - docker build -t alphata/web -f MyTestApp/Dockerfile.dev .

script:
- docker run alphata/web echo korami

after_success:
 - docker build -t alphata/api MyTestApp
 - docker build -t alphata/api MyTestApp.Api
 - docker build -t alphata/api MyTestApp.Worker
 - docker build -t alphata/nginx nginx
