
sudo: required
services:
 - docker

before_install:
 - docker build -t alphata/web -f MyTestApp/Dockerfile.dev .

script:
- echo "Done"

after_success:
 - docker build -t alphata/web ./MyTestApp
 - docker build -t alphata/api ./MyTestApp.Api
 - docker build -t alphata/worker ./MyTestApp.Worker
 - docker build -t alphata/nginx ./nginx

 - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
 - docker push alphata/web
 - docker push alphata/api
 - docker push alphata/worker
 - docker push alphata/nginx