
sudo: required
services:
 - docker

before_install:
 - docker build -t alphata/web-dev -f MyTestApp/Dockerfile.dev .

script:
- echo "Done"

after_success:
 - docker build -t alphata/web -f MyTestApp/Dockerfile .
 - docker build -t alphata/api -f MyTestApp.Api/Dockerfile .
 - docker build -t alphata/worker -f MyTestApp.Worker/Dockerfile .
 - docker build -t alphata/nginx -f nginx/Dockerfile .

 - echo '$DOCKER_PASSWORD' | docker login -u "$DOCKER_ID" --password-stdin
 - docker push alphata/web
 - docker push alphata/api
 - docker push alphata/worker
 - docker push alphata/nginx