language: csharp
sudo: required
dist: trusty
mono: none
dotnet: 3.0
services:
   - docker
os:
   - linux

before_install:
    - docker build -t alphata/docker-test -f Dockerfile.dev .

 script:
    - docker run alphata/docker-test echo korami