apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-persistent-volume-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce # *ReadOnlyMany - multiple nodes can read | *ReadWriteMany - multiple nodes can read/write
  resources:
    requests:
      storage: 2Gi