apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations: 
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/default-backend: web-cluster-ip-service
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
   - http:
      paths:
        - path: / 
          backend:
            serviceName: web-cluster-ip-service
            servicePort: 3000
        - path: /api/
          backend:
            serviceName: api-cluster-ip-service
            servicePort: 7000