output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}
 output "cluster_config_map" {
   description = "A kubernetes configuration to authenticate to this EKS cluster."
   value       = module.eks.config_map_aws_auth
}


output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "redis_host" {
  value = aws_elasticache_cluster.redis.cluster_address
}

output "redis_endpoint" {
  value = aws_elasticache_cluster.redis.configuration_endpoint
}

output "postgres_host" {
  value = aws_db_instance.postgres_db.address
}

output "postgres_endpoint" {
  value = aws_db_instance.postgres_db.endpoint
}

